env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - google
  - plugin:@typescript-eslint/recommended
  - prettier
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
  - "@typescript-eslint"
  - react-hooks
rules:
  react/prop-types: "off"
  react-hooks/rules-of-hooks: "error" # Checks rules of Hooks
  react-hooks/exhaustive-deps: "warn" # Checks effect dependencies
  require-jsdoc: "off"
  valid-jsdoc: "off"
